### ISSUE TITLE
bug: `stWalletTest` sender balance error

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#531]
### Current behavior
Running `stWalletTest` will fail on the balance of the sender address:
```
[!] Case ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stWalletTest/walletKill.json failed:
walletKill_d0g0v0_Shanghai balance mismatch for 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b: expected 0x0000000000000000000000000000000000000000000000000de0b6b3a7521455, got 0x0000000000000000000000000000000000000000000000000de0b6b3a75213f0
```

**Comment by ClementWalter** [comment]
The 3 first tests should be flagged in the GAS issue. Everything GAS related is failing, in this context probably because the tx should revert with OOG but we don't revert it in kakarot

The walletKill is a call to SELFDESTRUCT, thus a increase in the balance, not sure why it's failing, should be flagged in SELFDESTRUCT failing case

**Comment by greged93** [comment]
closed, everything has been moved to the correct detailed issue
